// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Enterwell.CI.Changelog.VSIX
{
    internal sealed partial class Vsix
    {
        public const string Id = "fbb23368-981a-4001-80ee-d3d3f930ed85";
        public const string Name = "Enterwell Changelog Adder";
        public const string Description = @"This extension helps developers make easy notes on changes made to the their codebase.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Enterwell";
        public const string Tags = "";
    }
}
