// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Enterwell.CI.Changelog.VSIX
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSIXPackageString = "6af01837-13a8-43a7-862a-d81edb897f4d";
        public static Guid guidVSIXPackage = new Guid(guidVSIXPackageString);

        public const string guidVSIXPackageCmdSetString = "e2a9d4e5-33a0-4e98-ad0a-cda0dbae0af4";
        public static Guid guidVSIXPackageCmdSet = new Guid(guidVSIXPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int AddChangeCommandId = 0x0100;
    }
}