name: Release NPM package

# Variables
env:
  ROOT_PATH: Enterwell.CI.Changelog.CLI.NPM

on:
  workflow_call:
    secrets:
      GH_PAT:
        required: true
      NPM_TOKEN:
        required: true

jobs:
  # Check for changes
  check-changes:
    name: Check for changes
    uses: './.github/workflows/check-changes.yml'
    with:
      ROOT_PATH: Enterwell.CI.Changelog.CLI.NPM
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}

  # Release
  release:
    name: Release NPM package
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.ROOT_PATH }}
    needs: check-changes
    if: needs.check-changes.outputs.has_changes == 'true'

    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      # Defining what Node.js version to use
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      # Setup the npmrc configuration
      - name: Setup npmrc
        run: npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Bump version and update changelog
      - name: Changelog
        id: version-bump
        uses: Enterwell/ChangelogManager-GitHub-Action@v3
        with:
          should-bump-version: true
          changelog-location: ${{ env.ROOT_PATH }}
          changes-location: ${{ env.ROOT_PATH }}/changes
          path-to-project-file: ${{ env.ROOT_PATH }}/package.json

      # Publish the package
      - name: Publish package
        run: npm publish

      # Commit new changes
      - name: Commit changelog changes
        uses: EndBug/add-and-commit@v9
        with:
          pull: '--rebase --autostash'
          default_author: github_actions
          message: "[skip ci] [version-bump] [npm] Automated commit for version ${{ steps.version-bump.outputs.bumped-semantic-version }}"