name: Release Azure DevOps extension

# Variables
env:
  ROOT_PATH: Enterwell.CI.Changelog.DevOpsExtension

on:
  workflow_call:
    secrets:
      GH_PAT:
        required: true
      VS_MARKETPLACE_TOKEN:
        required: true

jobs:
  release:
    name: Release Azure DevOps extension
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.ROOT_PATH }}

    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      # Globally install TFX CLI
      - name: Install TFX CLI
        run: npm install -g tfx-cli

      # Update changelog
      - name: Changelog
        id: version-bump
        uses: Enterwell/ChangelogManager-GitHub-Action@v3
        with:
          should-bump-version: true
          changelog-location: ${{ env.ROOT_PATH }}
          changes-location: ${{ env.ROOT_PATH }}/changes
          path-to-project-file: ${{ env.ROOT_PATH }}/vss-extension.json

      # Process all tasks
      - name: Preparing tasks
        run: |
          for parent in ./*/ ; do
            parent_name=$(basename "$parent")

            # Exclude 'images' i 'changes'
            if [ "$parent_name" != "images" ] && [ "$parent_name" != "changes" ]; then
              echo "Processing task directory: $parent_name"

              # Iterate subfolders
              for sub in "$parent"*/ ; do
                sub_name=$(basename "$sub")

                echo "Processing version: $sub_name in $parent_name"

                cd "$sub"

                echo "Step 1 for $sub_name: NPM install..."
                npm i

                echo "Step 2 for $sub_name: Compiling Typescript..."
                npx tsc

                cd ../..
              done
            else
              echo "Skipping $parent_name"
            fi
          done
      
      # Once all tasks have been processed, publish the extension
      - name: Publishing the extension
        run: tfx extension publish --token ${{ secrets.VS_MARKETPLACE_TOKEN }} --share-with enterwell tehnozavod --rev-version

      # Commit new changes
      - name: Commit changelog changes
        uses: EndBug/add-and-commit@v9
        with:
          cwd: ${{ env.ROOT_PATH }}
          pull: '--rebase --autostash'
          default_author: github_actions
          add: "[changes, CHANGELOG.md, vss-extension.json]"
          message: "[skip ci] [version-bump] [devops] Automated commit for version ${{ steps.version-bump.outputs.bumped-semantic-version }}"