name: Release VS Code extension

# Variables
env:
  ROOT_PATH: Enterwell.CI.Changelog.VSCodeExtension

on:
  workflow_call:
    secrets:
      VSCE_PAT:
        required: true

jobs:
  release:
    name: Release VS Code extension
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.ROOT_PATH }}

    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Defining what .NET SDK to use
      - name: Use .NET 6.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      # Defining what Node.js version to use
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn
          cache-dependency-path: ${{ env.ROOT_PATH }}/yarn.lock

      # Bump version and update changelog
      - name: Changelog
        id: version-bump
        uses: Enterwell/ChangelogManager-GitHub-Action@v3
        with:
          should-bump-version: true
          changelog-location: ${{ env.ROOT_PATH }}
          changes-location: ${{ env.ROOT_PATH }}/changes
          path-to-project-file: ${{ env.ROOT_PATH }}/package.json

      # Commit new changes
      - name: Commit changelog changes
        uses: EndBug/add-and-commit@v9.1.4
        with:
          pull: '--rebase --autostash'
          message: "[skip ci] [version-bump] [vscode] Automated commit for version ${{ steps.version-bump.outputs.bumped-semantic-version }}"

      # Installing node dependencies using Yarn
      - name: Yarn install
        run: yarn install --frozen-lockfile

      # Compile and run linter
      - name: Compile and lint
        run: yarn pretest

      # Install @vscode/vsce globally
      - name: Install global @vscode/vsce
        run: yarn global add @vscode/vsce

      # Publish the extension
      - name: Publish extension
        run: vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}