name: Release

# Triggering the workflow on pushes to main
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Release VS Code extension
  release-vscode:
    uses: './.github/workflows/release-vscode.yml'
    secrets:
      VSCE_PAT: ${{ secrets.VSCE_PAT }}

  # Release Azure DevOps extension
  release-devops:
    uses: './.github/workflows/release-devops.yml'
    secrets:
      VS_MARKETPLACE_TOKEN: ${{ secrets.VSCE_PAT }}

  # Rest of the repository
  rest:
    name: Rest
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Defining what .NET SDK to use
      - name: Use .NET 6.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      
      # Bump version and update changelog
      - name: Bump version and update changelog
        id: version-bump
        uses: Enterwell/ChangelogManager-GitHub-Action@v3
        with:
          should-bump-version: true
          path-to-project-file: Enterwell.CI.Changelog/Enterwell.CI.Changelog.csproj
      
      # Committing new changes
      - name: Commit changes
        uses: EndBug/add-and-commit@v9.1.4
        with:
          message: "[skip ci] [version-bump] Automated commit for version ${{ steps.version-bump.outputs.bumped-semantic-version }}"