name: Release

# Triggering the workflow on pushes to main
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Release VS Code extension
  release-vscode:
    uses: './.github/workflows/release-vscode.yml'
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      VSCE_PAT: ${{ secrets.VSCE_PAT }}

  # Release Visual Studio extension
  release-vs:
    uses: './.github/workflows/release-vs.yml'
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      VSCE_PAT: ${{ secrets.VSCE_PAT }}

  # Release Azure DevOps extension
  release-devops:
    uses: './.github/workflows/release-devops.yml'
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      VSCE_PAT: ${{ secrets.VSCE_PAT }}

  # Release NPM package
  release-npm:
    uses: './.github/workflows/release-npm.yml'
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  # Rest of the repository
  release-rest:
    uses: './.github/workflows/release-rest.yml'
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}